# Arewa DataScience Academy
### Deep Learning Cohort 1.0

#### Name: Ibrahim Ismaila
#### Email: ibrahim5322022@hotmail.com
#### Title: Week 1 Solution

## PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
tensor1 = torch.rand((7,7))
print(tensor1)

tensor([[0.4797, 0.4892, 0.9066, 0.3802, 0.4879, 0.3713, 0.2966],
        [0.3263, 0.5733, 0.5921, 0.3713, 0.6732, 0.8609, 0.6903],
        [0.3262, 0.9029, 0.5030, 0.1631, 0.3134, 0.0783, 0.2723],
        [0.9483, 0.0799, 0.9278, 0.6182, 0.2941, 0.5965, 0.0434],
        [0.8891, 0.3037, 0.9106, 0.5299, 0.3868, 0.7501, 0.2069],
        [0.5827, 0.2886, 0.3186, 0.5116, 0.2967, 0.5422, 0.3590],
        [0.8822, 0.0351, 0.7689, 0.1190, 0.6303, 0.6013, 0.0483]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
tensor2 = torch.rand((1,7))
# Perform matrix multiplication
multi2 = torch.matmul(tensor1, tensor2.T)
print(multi2)

tensor([[1.7928],
        [2.1268],
        [1.2513],
        [2.1023],
        [2.2697],
        [1.6783],
        [1.7328]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor1_seed = torch.rand((7,7))
tensor2_seed = torch.rand((1,7))

# Matrix multiply tensors
multi_seed = torch.matmul(tensor1_seed, tensor2_seed.T)
print(multi_seed)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
if torch.cuda.is_available():
    torch.cuda.manual_seed(1234)
    print("GPU is available. Random seed set.")
else:
    print("GPU is not available. Random seed not set.")

GPU is available. Random seed set.



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
# Create two random tensors on GPU
tensor_A = torch.rand((2,3)).to(device)
tensor_B = torch.rand((2,3)).to(device)
print(tensor_A, tensor_B)

Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B
Multi4 = torch.matmul(tensor_A, tensor_B.T)
print(Multi4, Multi4.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max
max_value = torch.max(Multi4)

# Find min
min_value = torch.min(Multi4)

print(f"Maximum value: {max_value}")
print(f"Minimum value: {min_value}")

Maximum value: 0.5617256760597229
Minimum value: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max
max_index = torch.argmax(Multi4)

# Find arg min
min_index = torch.argmin(Multi4)

print(f"Index of maximum value: {max_index}")
print(f"Index of minimum value: {min_index}")

Index of maximum value: 3
Index of minimum value: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor5 = torch.rand((1,1,1,10))

# Remove single dimensions
tensor5_squeezed = tensor5.squeeze()

# Print out tensors and their shapes
print(tensor5, tensor5.shape)
print(tensor5_squeezed, tensor5_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
