# Arewa DataScience Academy
### Deep Learning Cohort 1.0

### WEEK 1 Exercises

## PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
tensor1 = torch.rand((7,7))
print(tensor1)

tensor([[0.2292, 0.5549, 0.3503, 0.5675, 0.5664, 0.8527, 0.8922],
        [0.4880, 0.2025, 0.8637, 0.2196, 0.7555, 0.3179, 0.0339],
        [0.4512, 0.5591, 0.8794, 0.8444, 0.6228, 0.4261, 0.2479],
        [0.8657, 0.2016, 0.7768, 0.0925, 0.5651, 0.9044, 0.4860],
        [0.1074, 0.3187, 0.2302, 0.6771, 0.3807, 0.8673, 0.7737],
        [0.4899, 0.7620, 0.1074, 0.5381, 0.2102, 0.4411, 0.8237],
        [0.1289, 0.1591, 0.6720, 0.7423, 0.9937, 0.6030, 0.3028]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
tensor2 = torch.rand((1,7))
# Perform matrix multiplication
multi2 = torch.matmul(tensor1, tensor2.T)
print(multi2)

tensor([[2.0292],
        [1.8126],
        [2.3249],
        [2.4944],
        [1.5611],
        [1.8839],
        [1.7176]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor1_seed = torch.rand((7,7))
tensor2_seed = torch.rand((1,7))

# Matrix multiply tensors
multi_seed = torch.matmul(tensor1_seed, tensor2_seed.T)
print(multi_seed)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
if torch.cuda.is_available():
    torch.cuda.manual_seed(1234)
    print("GPU is available. Random seed set.")
else:
    print("GPU is not available. Random seed not set.")

GPU is available. Random seed set.



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
# Create two random tensors on GPU
tensor_A = torch.rand((2,3)).to(device)
tensor_B = torch.rand((2,3)).to(device)
print(tensor_A, tensor_B)

Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
Multi4 = torch.matmul(tensor_A, tensor_B.T)
print(Multi4, Multi4.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
max_value = torch.max(Multi4)

# Find min
min_value = torch.min(Multi4)

print(f"Maximum value: {max_value}")
print(f"Minimum value: {min_value}")

Maximum value: 0.5617256760597229
Minimum value: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
max_index = torch.argmax(Multi4)

# Find arg min
min_index = torch.argmin(Multi4)

print(f"Index of maximum value: {max_index}")
print(f"Index of minimum value: {min_index}")

Index of maximum value: 3
Index of minimum value: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor5 = torch.rand((1,1,1,10))

# Remove single dimensions
tensor5_squeezed = tensor5.squeeze()

# Print out tensors and their shapes
print(tensor5, tensor5.shape)
print(tensor5_squeezed, tensor5_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
